- name: Install Chrome, VS Code, Discord, and WeChat
  community.general.homebrew_cask:
    name: [google-chrome, visual-studio-code, discord, wechat]
    state: present

- name: Install CLI tools
  community.general.homebrew:
    name: [gh, sl, fastfetch, btop, gti, cowsay, awscli]
    state: present
