- hosts: localhost
  connection: local
  vars:
    dotfiles_dir: "{{ playbook_dir | dirname }}"
    user_home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Tap nikitabobko/tap for aerospace
      community.general.homebrew_tap:
        name: nikitabobko/tap
        state: present

    - name: Install macOS cask packages
      community.general.homebrew_cask:
        name: [nikitabobko/tap/aerospace, karabiner-elements]
        state: present

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ user_home }}/.config/aerospace"
        - "{{ user_home }}/.config/karabiner"

    - name: Create symlinks for macOS dotfiles
      file:
        src: "{{ dotfiles_dir }}/{{ item.src }}"
        dest: "{{ user_home }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: 'config/aerospace/aerospace.toml', dest: '.config/aerospace/aerospace.toml' }
        - { src: 'config/karabiner/karabiner.json', dest: '.config/karabiner/karabiner.json' }
