set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#(pane_current_path}"

set -g mouse on
set -g default-terminal "screen-256color"
