on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [bootstrap.sh]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v7
      - run: |
          mkdir out
          cp bootstrap.sh out/index.html
          echo "dotfiles.kevinjin.dev" > out/CNAME
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out
      - uses: actions/deploy-pages@v4
